# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    # Test name: Untitled
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://localhost:3333/")
    # 2 | setWindowSize | 1936x1048 | 
    self.driver.set_window_size(1936, 1048)
    # 3 | click | id=:r1:-tab-1 | 
    self.driver.find_element(By.ID, ":r1:-tab-1").click()
    # 4 | click | css=#add-director-btn path | 
    self.driver.find_element(By.CSS_SELECTOR, "#add-director-btn path").click()
    # 5 | click | id=name | 
    self.driver.find_element(By.ID, "name").click()
    # 6 | type | id=name | stanley kubrick
    self.driver.find_element(By.ID, "name").send_keys("stanley kubrick")
    # 7 | mouseDownAt | css=.h-min > .flex | 66,17.5
    element = self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 8 | mouseMoveAt | css=.h-min > .flex | 66,17.5
    element = self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 9 | mouseUpAt | css=.h-min > .flex | 66,17.5
    element = self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 10 | click | css=.h-min > .flex | 
    self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex").click()
    # 11 | click | css=#add-director-btn .w-16 | 
    self.driver.find_element(By.CSS_SELECTOR, "#add-director-btn .w-16").click()
    # 12 | click | id=name | 
    self.driver.find_element(By.ID, "name").click()
    # 13 | click | id=name | 
    self.driver.find_element(By.ID, "name").click()
    # 14 | type | id=name | Quentin Tarantino
    self.driver.find_element(By.ID, "name").send_keys("Quentin Tarantino")
    # 15 | click | css=.h-min > .flex | 
    self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex").click()
    # 16 | mouseOver | css=.h-min > .flex | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 17 | click | id=:r1:-tab-0 | 
    self.driver.find_element(By.ID, ":r1:-tab-0").click()
    # 18 | click | css=#add-movie-btn .w-16 | 
    self.driver.find_element(By.CSS_SELECTOR, "#add-movie-btn .w-16").click()
    # 19 | click | id=title | 
    self.driver.find_element(By.ID, "title").click()
    # 20 | type | id=title | pulp fiction
    self.driver.find_element(By.ID, "title").send_keys("pulp fiction")
    # 21 | click | id=description | 
    self.driver.find_element(By.ID, "description").click()
    # 22 | type | id=description | la mejor de tarantino
    self.driver.find_element(By.ID, "description").send_keys("la mejor de tarantino")
    # 23 | click | id=year | 
    self.driver.find_element(By.ID, "year").click()
    # 24 | type | id=year | 1994
    self.driver.find_element(By.ID, "year").send_keys("1994")
    # 25 | click | id=director_id | 
    self.driver.find_element(By.ID, "director_id").click()
    # 26 | select | id=director_id | label=Quentin Tarantino
    dropdown = self.driver.find_element(By.ID, "director_id")
    dropdown.find_element(By.XPATH, "//option[. = 'Quentin Tarantino']").click()
    # 27 | click | css=.h-min > .flex | 
    self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex").click()
    # 28 | click | css=#add-movie-btn > .flex | 
    self.driver.find_element(By.CSS_SELECTOR, "#add-movie-btn > .flex").click()
    # 29 | mouseOver | css=#add-movie-btn > .flex | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#add-movie-btn > .flex")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 30 | mouseOut | css=#add-movie-btn > .flex | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 31 | click | id=title | 
    self.driver.find_element(By.ID, "title").click()
    # 32 | type | id=title | odisea del espacio
    self.driver.find_element(By.ID, "title").send_keys("odisea del espacio")
    # 33 | click | id=description | 
    self.driver.find_element(By.ID, "description").click()
    # 34 | type | id=description | mi preferida de Kubrick
    self.driver.find_element(By.ID, "description").send_keys("mi preferida de Kubrick")
    # 35 | click | css=.flex-1 | 
    self.driver.find_element(By.CSS_SELECTOR, ".flex-1").click()
    # 36 | click | id=year | 
    self.driver.find_element(By.ID, "year").click()
    # 37 | type | id=year | 1968
    self.driver.find_element(By.ID, "year").send_keys("1968")
    # 38 | click | id=director_id | 
    self.driver.find_element(By.ID, "director_id").click()
    # 39 | select | id=director_id | label=stanley kubrick
    dropdown = self.driver.find_element(By.ID, "director_id")
    dropdown.find_element(By.XPATH, "//option[. = 'stanley kubrick']").click()
    # 40 | click | css=.h-min > .flex | 
    self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex").click()
    # 41 | click | css=#add-movie-btn .w-16 | 
    self.driver.find_element(By.CSS_SELECTOR, "#add-movie-btn .w-16").click()
    # 42 | click | id=title | 
    self.driver.find_element(By.ID, "title").click()
    # 43 | type | id=title | interstelar
    self.driver.find_element(By.ID, "title").send_keys("interstelar")
    # 44 | click | id=description | 
    self.driver.find_element(By.ID, "description").click()
    # 45 | type | id=description | la mejor representacion de un agujero negro
    self.driver.find_element(By.ID, "description").send_keys("la mejor representacion de un agujero negro")
    # 46 | click | id=year | 
    self.driver.find_element(By.ID, "year").click()
    # 47 | type | id=year | 2014
    self.driver.find_element(By.ID, "year").send_keys("2014")
    # 48 | click | id=director_id | 
    self.driver.find_element(By.ID, "director_id").click()
    # 49 | select | id=director_id | label=Cristopher Nolan
    dropdown = self.driver.find_element(By.ID, "director_id")
    dropdown.find_element(By.XPATH, "//option[. = 'Cristopher Nolan']").click()
    # 50 | mouseDownAt | css=.h-min > .flex | 53,15.5
    element = self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 51 | mouseMoveAt | css=.h-min > .flex | 53,15.5
    element = self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 52 | mouseUpAt | css=.h-min > .flex | 53,15.5
    element = self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 53 | click | css=.h-min > .flex | 
    self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex").click()
    # 54 | click | css=#add-movie-btn .w-16 | 
    self.driver.find_element(By.CSS_SELECTOR, "#add-movie-btn .w-16").click()
    # 55 | click | id=title | 
    self.driver.find_element(By.ID, "title").click()
    # 56 | type | id=title | tenet
    self.driver.find_element(By.ID, "title").send_keys("tenet")
    # 57 | click | id=description | 
    self.driver.find_element(By.ID, "description").click()
    # 58 | type | id=description | nadie entiende esta pelicula
    self.driver.find_element(By.ID, "description").send_keys("nadie entiende esta pelicula")
    # 59 | click | id=year | 
    self.driver.find_element(By.ID, "year").click()
    # 60 | type | id=year | 2020
    self.driver.find_element(By.ID, "year").send_keys("2020")
    # 61 | click | id=director_id | 
    self.driver.find_element(By.ID, "director_id").click()
    # 62 | select | id=director_id | label=Cristopher Nolan
    dropdown = self.driver.find_element(By.ID, "director_id")
    dropdown.find_element(By.XPATH, "//option[. = 'Cristopher Nolan']").click()
    # 63 | click | css=.h-min > .flex | 
    self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex").click()
    # 64 | close |  | 
    self.driver.close()
  
